exceptions homework
abulavs/codelex-exercises pull request #13
Opened 2022-03-23 08:06 UTC by abulavs

2022-03-30 17:07 UTC, NilsKula requested changes

2022-03-30 17:07 UTC, NilsKula commented on src/main/java/io/codelex/exceptions/practice/Exercise2.java
>  public class Exercise2 {
After each try{} block put a catch{} block which catches the exception, prints a stack trace, and throws the exception object to its caller.

2022-03-31 22:17 UTC, abulavs commented
itkā salaboju :)

2022-04-14 09:19 UTC, NilsKula approved these changes
visas meteodēs varēji vienkārši `throw e` bet nu jā var throw arī new, kad gribi kaut ko custom pielikt

2022-04-28 20:50 UTC, merged