Collections homework
abulavs/codelex-exercises pull request #14
Opened 2022-03-24 09:06 UTC by abulavs

2022-04-10 11:36 UTC, NilsKula requested changes

2022-04-10 11:36 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Exercise1.java
> +            if (car.equals("Audi") || car.equals("BMW") || car.equals("Mercedes") || car.equals("VolksWagen"))
curly braces
palīgmetode vai arī kā static listu visas germany markas

2022-04-10 11:36 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Exercise5.java
> +        int sum = 0;
labāk no metodes atgriez vienkārši sum

2022-04-10 11:36 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/flightPlanner/FlightsList.java
> +                    throw new Exception();
šķiet, ka tev nevajag šeit papildus izmest excpetion

2022-04-10 11:36 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/flightPlanner/FlightsList.java
> +            if (fligtsObject.get(i).getStartCity().equals(lastCity) && !fligtsObject.get(i).getEndCity().equals(lastCity)) {
vismaz uz vienu palīgmetodi

2022-04-10 11:36 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/flightPlanner/FlightPlanner.java
> +    private static final String file = "/collections/flights.txt";
`FILE`, caps for constants

2022-04-10 11:36 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +    private static void FillScoresList(String[] scoresArray, List<Integer> scoresList) {
ar mazo

2022-04-10 11:36 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneDirectory.java
> +        String key = phoneEntry.getPhoneBookList(name);
`return phoneEntry.getPhoneBookList(name);`

2022-04-10 11:36 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneDirectory.java
> +    PhoneEntry phoneEntry = new PhoneEntry();
private

2022-04-29 07:26 UTC, abulavs commented on src/main/java/io/codelex/collections/practice/Exercise5.java
> +        int sum = 0;
Nezinu vai labāk, bet vismaz savādāk :)

2022-05-01 12:34 UTC, janistumpelis approved these changes

2022-05-04 19:36 UTC, merged