Polymorphism
abulavs/codelex-exercises pull request #15
Opened 2022-03-27 20:50 UTC by abulavs

2022-04-21 16:15 UTC, NilsKula requested changes

2022-04-21 16:15 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise1/CarBoost.java
> +    void speedUp();
šis un `slowdown` pārklājās ar `Car` interface

2022-04-21 16:15 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise1/Bmw.java
> +    public void speedUp() {
lieto @Override

2022-04-21 16:15 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise1/Car.java
> +public interface Car {
trūkst start engine 
un variable definē klasē

2022-04-21 16:15 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise2/Firework.java
> +    public void playSound() {
override

2022-04-21 16:15 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise6/Food.java
> +    Integer quantity;
private

2022-04-21 16:15 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise6/Meat.java
> +    String meatName;
private

2022-04-21 16:15 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise6/Mammal.java
> +    String livingRegion;
private

2022-05-01 12:36 UTC, janistumpelis approved these changes

2022-05-04 19:37 UTC, merged