Date and time
abulavs/codelex-exercises pull request #9
Opened 2022-03-14 22:48 UTC by abulavs

2022-03-21 20:45 UTC, NilsKula requested changes

2022-03-21 20:45 UTC, NilsKula commented on src/main/java/io/codelex/DateAndTime/Exercise1.java
> +            if (!(date1.getDayOfWeek().equals(DayOfWeek.SATURDAY)) && !(date1.getDayOfWeek().equals(DayOfWeek.SUNDAY))) {
palīgmetode būtu tieši laikā, piemēram,
`if(isWorkingDay(...)` way more redable

2022-03-21 20:45 UTC, NilsKula commented on src/main/java/io/codelex/DateAndTime/Exercise2.java
> +            if (startDate.getMonth().equals(requestDate.getMonth()) && startDate.getYear() == (requestDate.getYear())) {
šeit arī taspats kas 1. uzdevumā

2022-03-21 20:45 UTC, NilsKula commented on src/main/java/io/codelex/DateAndTime/Intersection.java
> +    LocalDate firstStart;
visi variables private

2022-03-21 20:45 UTC, NilsKula commented on src/main/java/io/codelex/DateAndTime/Intersection.java
> +            intersectionStart = secondStart;
set static fields from static methods or the other way
arī šīs 3 rindiņas iff blokā atkaŗtojas tik mainas variabļi, mierīgi var izveidot palīgmetodi kam padot šīs 3 vērtības

2022-03-21 20:45 UTC, NilsKula commented on src/main/java/io/codelex/DateAndTime/Intersection.java
> +        } else if (firstEnd.isBefore(secondEnd) && firstStart.isBefore(secondStart)) {
`isBefore() && isBefore()` arīv ien jau varu izskaitīt 5x, uz palīgmetodi

2022-03-27 12:41 UTC, abulavs commented on src/main/java/io/codelex/DateAndTime/Intersection.java
> +            intersectionStart = secondStart;
checkIntersection() jau ir palīgmetode kura tiek izsaukta no DatePeriod

2022-03-30 08:23 UTC, NilsKula commented on src/main/java/io/codelex/DateAndTime/Intersection.java
> +            intersectionStart = secondStart;
nu jā, bet palīgmetodes pašam `checkIntersection()` :smile:

2022-03-30 08:25 UTC, NilsKula approved these changes

2022-03-30 10:03 UTC, merged